### ISSUE TITLE
we cannot reproduce with your scripts

### ISSUE THREAD

**Issue by liuzhen** [qzhang-1a/redis-test#1]
according to our experiment,
https://github.com/antirez/redis/blob/unstable/src/cluster.c#L1878
handles the case you described.

please verify your steps.

we are facing similar issue, but not the steps as yours;

**Comment by qzhang-1a** [comment]
Hello @liuzhen ,

I have rerun my tests. The reproducer works. Are you running with the same redis version 4.0.8 ? 
The reproducer also works with redis 5.0.5.
The issue here is that redis cluster propagate topology to known nodes by IP but not redis node ID.
So when a node is killed and another new node reuses its IP, the new node will make the link between 2 clusters and merge them together. This could happen in a cloud environment like openshift.

I don't see how this could be fixed by https://github.com/redis/redis/blob/unstable/src/cluster.c#L1878

However, we have used a [workaround ](https://github.com/redis/redis/pull/6129) to fix this issue, by adding a cluster name parameter to the config and check this cluster name when doing handshake.
